GMAIL:
 BULLETIN_EMAIL_ADDRESS: ABC
 MY_EMAIL_ADDRESS: ABC
 MY_GMAIL_APP_PASSWORD: ABC
 BULLET_EMAIL_ADDRESS_APP_PASSWORD: ABC

REDDIT:
 REDDIT_CLIENT_ID: ABC
 REDDIT_CLIENT_SECRET: ABC
 REDDIT_PASSWORD: ABC
 REDDIT_USERNAME: ABC
 REDDIT_USER_AGENT: ABC

GOOGLE:
 GOOGLE_API_KEY: ABC
 GOOGLE_CLIENT_SECRETS_PATH: ABC